### ISSUE TITLE
Quality selection when streaming from YouTube

### ISSUE THREAD

**Issue by sdmtr** [khloke/play-to-xbmc-chrome#106]
My connection at home has trouble streaming 1080p videos from YouTube, so it would be wonderful to be able to choose a lower quality when sending the stream to Kodi.

I've tried selecting a lower quality on the YouTube player before sending the stream but that doesn't seem to make any difference, Play to Kodi seems to just send the highest quality stream available regardless.

**Comment by maciex** [comment]
Does it make any difference when playing videos directly from Youtube plugin?

**Comment by sdmtr** [comment]
Sorry, I don't understand the question. I'm using the Chrome plugin, all I'm doing is navigating (in Chrome) to the video I want to watch, selecting a lower quality stream (e.g, 720p), then clicking the extension button in the toolbar, then clicking the "Play now" button in the extension window, at which point the video starts streaming in Kodi at the highest available quality rather than 720p. 

Just in case Kodi actually *was* streaming at 720p and I was simply unable to tell the difference visually, I also tried setting the quality to 144p since that would be unmistakeable, but that made no difference, Kodi still streams at the highest available quality.

**Comment by martijnvermaat** [comment]
In the YouTube plugin configuration (so in Kodi), is the default streaming bitrate set to highest available? If so, does changing this help?

play-to-xbmc just passes the YouTube video URL to the Kodi YouTube plugin as far as I know, so I would expect its configuration applies.

**Comment by sdmtr** [comment]
Sorry for the late reply, I've been away. You're spot on, it's all down to the YouTube plugin, I changed the settings so that it now prompts me to select the quality before playing. Thank you for your help.
