### ISSUE TITLE
XPI release

### ISSUE THREAD

**Issue by alfieoriginal** [khloke/play-to-xbmc-chrome#108]
Could you please add a .xpi release?

**Comment by khloke** [comment]
You can get the Firefox XPI releases from @maciex 's fork.
https://github.com/maciex/play-to-kodi/releases

**Comment by alfieoriginal** [comment]
Thank you. I saw it before. But I think is not up to date.

**Comment by khloke** [comment]
It's not too far off. I don't work on any of the firefox related changes, it's best you talk to @maciex about merging changes. Sorry.
