### ISSUE TITLE
Incompatible with Twitch.tv version 2.0 add-on

### ISSUE THREAD

**Issue by StarTrekFace** [khloke/play-to-xbmc-chrome#113]
The current branch of the Twitch.tv add-on doesn't work well anymore and they're close to releasing a new 2.0 version. 2.0 is at alpha12 right now and it works great - but the changes have broken Play To Kodi support. When I send a stream to Kodi running the Twitch.tv 2.0a12 add-on, I get the busy indicator for half a second and then nothing happens.

With Kodi debug logging on I see this trying to send a stream with the new version of the add-on:
```
11:42:28.303 T:1792   DEBUG: Twitch: Version: |2.0.0~alpha12| Kodi Version: |17.1 Git:20170320-fc1619b| -> |17|1|fc|1619|20170320-fc1619b| (ENCODED)
11:42:28.303 T:1792   DEBUG: Twitch: Queries: |{'mode': 'main'}| Args: |['plugin://plugin.video.twitch/playLive/capcomfighters/-2/', '1', '']|
11:42:28.303 T:1792    INFO: CPythonInvoker(8, C:\Users\username\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\__run__.py): script aborted
11:42:28.306 T:1792    INFO: Python script stopped
11:42:28.306 T:1792   DEBUG: Thread LanguageInvoker 1792 terminating
11:42:28.316 T:3756   DEBUG: Thread scriptobs 3756 terminating
11:42:28.335 T:1240   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/capcomfighters/-2/]
```
I don't know if this is applicable but this is what is logged when playing a stream from the add-on natively:

```
11:53:36.727 T:3196   DEBUG: Twitch: Version: |2.0.0~alpha12| Kodi Version: |17.1 Git:20170320-fc1619b| -> |17|1|fc|1619|20170320-fc1619b| (ENCODED)
11:53:36.727 T:3196   DEBUG: Twitch: Queries: |{'channel_id': '36616300', 'mode': 'play', 'name': 'capcomfighters'}| Args: |['plugin://plugin.video.twitch/', '4', '?channel_id=36616300&mode=play&name=capcomfighters']|
11:53:36.727 T:3196  NOTICE: Twitch: Calling |play| for mode |play| with pos args |[]| and kwargs |{'channel_id': '36616300', 'name': 'capcomfighters'}|
```

**Comment by StarTrekFace** [comment]
The easiest way I found for tracking the 2.0 add-on was installing the repository at https://raw.githubusercontent.com/anxdpanic/__testing_repository/master/zips/repository.anxdpanic.testing/repository.anxdpanic.testing-0.0.1.zip

[source](https://github.com/MrSprigster/Twitch-on-Kodi/issues/235)

**Comment by khloke** [comment]
Support has been added. Will be included in the next update.

https://github.com/khloke/play-to-xbmc-chrome/commit/e70d756367292a32a07ef5e3ce493ae0d144d7ba

**Comment by henriklb** [comment]
eta on that update? Twitch for kodi 2.0 is currently live

**Comment by khloke** [comment]
I've just pushed version 1.8.1, which includes this update. You should get it in a few days.

**Comment by henriklb** [comment]
Thank you for doing the work, I'm on 1.8.1 now :)
