### ISSUE TITLE
Firefox port

### ISSUE THREAD

**Issue by mightynerd** [khloke/play-to-xbmc-chrome#122]
This extension seems to work fine when loaded into Firefox Nightly 57.0a1. I can change the settings, connect to Kodi, send Youtube videos and control the playback with no issues. I suggest that the extension should be tested and submitted as an Firefox add-on.
![2017-08-19_18-32-53](https://user-images.githubusercontent.com/5666717/29488594-60629f08-850e-11e7-86d6-cdd5c733e817.png)

**Comment by maciex** [comment]
The Add-on is already submitted to addons.mozilla.org.

You can view/install it from:
https://addons.mozilla.org/en-US/firefox/addon/play-to-kodi4/

I'm managing [Firefox issues in a separate repository](https://github.com/maciex/play-to-kodi), as @khloke suggested to do it in a separate repository (Issue #107).

**Comment by maciex** [comment]
I forgot to add that the Add-on is waiting for review. After that it will be listed (searchable) on addons.mozilla.org, right now it's visible via direct link.

**Comment by mightynerd** [comment]
That explains why I couldn't find it. Thank you!
