### ISSUE TITLE
Mouse scroll wheel doesn't move volume slider

### ISSUE THREAD

**Issue by Uroshi** [khloke/play-to-xbmc-chrome#133]
Hello

My configuration:
Windows 7 Home Premium 64bit
Firefox 57.0.2 64 bit

As I have mentioned in the subject, mouse scroll wheel doesn't move volume slider.
This isn't happening with Chrome on the same system

Best regards

**Comment by maciex** [comment]
Confirmed on:
Browser: Firefox 57.0.2 (64bit)
OS: Arch Linux

**Comment by maciex** [comment]
Oups, sorry, this is khloke's master repository. Firefox issues please report to my fork:
https://github.com/maciex/play-to-kodi

**Comment by khloke** [comment]
Issue limited to Firefox.
