### ISSUE TITLE
Please publish version 1.9.1 to fix compatibility with Twitch add-on 2.1.0

### ISSUE THREAD

**Issue by parasyte** [khloke/play-to-xbmc-chrome#143]
https://github.com/khloke/play-to-xbmc-chrome/pull/131 was merged into master, but has not been published to the chrome web store. Twitch support is currently broken. I have to manually patch the extension to get it working. It's a pain because Chrome frequently reloads the extension and loses the patch.

**Comment by parasyte** [comment]
See also #126

**Comment by khloke** [comment]
Done. It should be live in about 24 hrs.
