### ISSUE TITLE
Extension removed from Chrome Web Store

### ISSUE THREAD

**Issue by felipebrauna** [khloke/play-to-xbmc-chrome#156]
Hi guys.
I believe the extension was removed from de Chrome Web Store, at least the one in the link below:
https://chrome.google.com/webstore/detail/fncjhcjfnnooidlkijollckpakkebden

If I´m worng, please tell me.
Regards.

**Comment by khloke** [comment]
You’re right. Apparently google didn’t like some of the sites that were supported, although not mentioned in the description. I’ll probably remove them from the master branch and rebuild it for the chrome store, then keep the others in a different branch for people who want them.

**Comment by khloke** [comment]
I have submitted a new version for Google to review. Hopefully there are no other problems.

**Comment by khloke** [comment]
It is now back on the Chrome store.

**Comment by felipebrauna** [comment]
Thanks!
