### ISSUE TITLE
Installing it on a fresh chrome gives errors on the manifest

### ISSUE THREAD

**Issue by djmulder** [khloke/play-to-xbmc-chrome#157]
Hey there,

So I reinstalled my computer and also chrome and noticed play to kodi isn't on the store anymore so I loaded it up from the 1.9.1 version on github.

Now after install it gives the following errors: 
![2019-04-27 17_56_53-Extensions](https://user-images.githubusercontent.com/10437793/56852024-ea70c700-6915-11e9-845f-b4b5f35ffbe1.png)
![2019-04-27 17_57_02-Extensions](https://user-images.githubusercontent.com/10437793/56852025-ea70c700-6915-11e9-9938-19bfb34dad1f.png)
![2019-04-27 17_56_40-Extensions](https://user-images.githubusercontent.com/10437793/56852026-ea70c700-6915-11e9-81f8-b9ca94baf36e.png)

**Comment by khloke** [comment]
I'm not sure what are the steps you took to load it, but I tried doing it using "Load unpacked extension" and it worked fine. Either way, I've submitted a new version for Google to review so you might not even need to do this in a few days.
