### ISSUE TITLE
Support for Dailymotion Games live streams

### ISSUE THREAD

**Issue by curunoir** [khloke/play-to-xbmc-chrome#38]
Hi,

thanks for your work it's brilliant. Do you think that the plugin could support Dailymotion games live streams such as http://games.dailymotion.com/live/ ?

Bye

**Comment by khloke** [comment]
Hi curunoir,

I'll look into it, but it depends on whether the dailymotion add-on or any other add-on on Kodi supports it.

Cheers,
KH

**Comment by curunoir** [comment]
Hi, thanks for your attention. I'm not sure if the Dailymotion addon handles it on every environments, some say on forums they can, some others including me can't.

**Comment by khloke** [comment]
I've added support for this in the latest push. However, if it doesn't work for you from the add-on, it won't work. I'm doing this first so when the add-on is fixed, it can be used right away.
