### ISSUE TITLE
Rebranding XBMC to Kodi

### ISSUE THREAD

**Issue by enen92** [khloke/play-to-xbmc-chrome#39]
Hey khloke,

Thanks for the extension. Use it for more than a year.
Just wondering that maybe it's time to rebrand xbmc words to kodi and xbmc logo to kodi's.

Cheers

**Comment by khloke** [comment]
Hah! I had the same thought not too long ago and the change had already been done in this commit:
https://github.com/khloke/play-to-xbmc-chrome/commit/5269db06d0f6e212005766462808db6ded16f2cb

It'll be out in the next release.

**Comment by enen92** [comment]
Cheers :)
When I have some time I'll try to add sopcast and acestream support to it

**Comment by khloke** [comment]
The acestream and sopcast you want might be supported already! Check out this merge: https://github.com/khloke/play-to-xbmc-chrome/commit/4f2ef293b2b72ac186d09da7343e5b4906e5a796

**Comment by enen92** [comment]
Holy crap, always one step behind :+1: . The PR looks good, I would change the title of the "beamed" stream to something like "Sent from Chrome" or similar.

name=title+sopcast'
&mode=1&name=acestream+title

But that's a minor. Looks like I should watch the repository :)

Well, thank you very much for your time and for the extension. 
Have a nice day
