### ISSUE TITLE
Support for Title in Playlist

### ISSUE THREAD

**Issue by xlogik** [khloke/play-to-xbmc-chrome#54]
I would like to see a drop-down or context menu option that allows the user to see the title/name of the upcoming video(s) in the playlist.

**Comment by khloke** [comment]
Unfortunately, this is not possible due to limitations on Kodi... it is explained in more detail in this link: https://github.com/khloke/play-to-xbmc-chrome/wiki/Frequently-Asked-Questions#q-can-you-add-a-feature-to-display-the-current-queue-list-in-the-extension
