### ISSUE TITLE
Pause current playing

### ISSUE THREAD

**Issue by Andulien** [khloke/play-to-xbmc-chrome#56]
Feature Reuqest:
When hitting "Play to Kodi" the current playing Youtube Video in Chrome should be paused.

Keep up the good work :)

**Comment by khloke** [comment]
Sound reasonable. Will look into it.

**Comment by Andulien** [comment]
Sounds great. Looking forward to it :)
Might have a look here: https://developers.google.com/youtube/js_api_reference?csw=1

player.pauseVideo():Void

Let me know when you updated it, I'm happy to test.

**Comment by Andulien** [comment]
When hitting Play now on Youtube the new option doesn't work "Videos on YouTube, Vessel and AnimeLab will auto pause when sent to Kodi."

**Comment by khloke** [comment]
Sorry, this only works when using the context menu for YouTube at the
moment. Which is why I haven't mark this as compete. My bad I forgot to
point this out in the changelog.

**Comment by Andulien** [comment]
Commit: 89a9ae3
Working with the newest Version 1.7.5.1. Just tested it :+1: 
When hitting PlayNow on the Chrome Icon, it will pause the current playing tab.

Question: Should this also be added for Queued and PlayNext?

**Comment by khloke** [comment]
I intend to make this work with Queue only when there is nothing playing at
the moment and it starts playing but not when adding to a queue. As for
play next, I won't make it pause for the same reason as queuing.  I think
it makes more sense that way.
