### ISSUE TITLE
Show what is Queued

### ISSUE THREAD

**Issue by Andulien** [khloke/play-to-xbmc-chrome#59]
Hi there,

so when queuing several different Youtube Videos, currently you can't see what you have queued and remove an accidentally queued video or sort them. Would be a nice feature to be added here :)

Keep up the good work.

**Comment by khloke** [comment]
Unfortunately this is not possible. You can read more about it here: https://github.com/khloke/play-to-xbmc-chrome/wiki/Frequently-Asked-Questions#q-can-you-add-a-feature-to-display-the-current-queue-list-in-the-extension
