### ISSUE TITLE
Youtube queue playlist not working

### ISSUE THREAD

**Issue by tbitowt** [khloke/play-to-xbmc-chrome#63]
Hi,

I'm having trouble with playlist queue in youtube,

I have tried several ways to do it and none is working.

My usecases:

UC1
Steps:
- Go to playlist site like:
 - https://www.youtube.com/playlist?list=PLdisRIh1ocHm0gR6KI9rYCcNHNRgD6EcD
- Click "Queue Playlist" in dropdown menu of plugin

Result
- Playlist not added to queue
- nothing happens

UC2
Steps:
- Open playlist
- Click "Play All"
- Click "Queue playlist" in plugin menu

Result:
- Playlist not added to queue
- nothing happens

Am I doing something wrong or it's a bug?

**Comment by khloke** [comment]
Hi tbitowt, 

It seems like Google has just deprecated the API that the extension is using. I will have to update it to use the updated API. Will take some time to work on this, sorry about the inconvenience.

Cheers,
KH

**Comment by khloke** [comment]
The fix for this has been released.
