### ISSUE TITLE
Cannot play direct video link if URL has a query string

### ISSUE THREAD

**Issue by Sazpaimon** [khloke/play-to-xbmc-chrome#81]
When trying to stream a direct video (avi, mp4, webm, etc), if the link contains a query string, the option to play on Kodi is not available. Removing the query string allows the video to play, however.

**Comment by khloke** [comment]
This is due to the lazy regex that I added in :(
I believe this is an easy fix, thanks for the report.

**Comment by khloke** [comment]
Fixed in code, will be in the next release.
