### ISSUE TITLE
Plans to support Firefox?

### ISSUE THREAD

**Issue by TheOddler** [khloke/play-to-xbmc-chrome#94]
Have you considered porting this to Firefox?

The only alternative I found for Firefox is https://addons.mozilla.org/en-US/firefox/addon/send-to-xbmc/ but that only supports Youtube links.

Thanks!

**Comment by martijnvermaat** [comment]
See #93

**Comment by TheOddler** [comment]
@martijnvermaat Thanks, missed that.
