### ISSUE TITLE
[Feature request] Support for Öppet Arkiv

### ISSUE THREAD

**Issue by tommyhansson** [khloke/play-to-xbmc-chrome#98]
Öppet Arkiv is a sister site for SVT Play which you already support. I have added some code to modules.js and tested it and it works perfect. See attached file.

[modules.js.txt](https://github.com/khloke/play-to-xbmc-chrome/files/499132/modules.js.txt)

**Comment by tommyhansson** [comment]
Oh, and I also fixed the SVT Play module which stopped working a while ago.

**Comment by maciex** [comment]
If you would fork the repo and request merge it would be easier for the author to merge your fix.
